name: Publish Indy Python
on:
  workflow_dispatch:
    inputs:
      indy_sdk_url:
        description: 'Indy SDK download URL'
        required: false
        type: string
      indy_postgres_url:
        description: 'Indy postgres download URL'
        required: false
        type: string
      indy_version:
        description: 'Indy SDK Version'
        required: false
        type: string
        default: '1.16.0'
      tag:
        description: 'Image tag'
        required: false
        type: string

env:
  INDY_SDK_TAG_URL: "https://codeload.github.com/hyperledger/indy-sdk/tar.gz/refs/tags/"

jobs:
  publish-image:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    name: Publish Indy Python
    runs-on: ubuntu-latest
    steps:
      - name: Gather image info
        id: info
        run: |
          echo "::set-output name=repo-owner::${GITHUB_REPOSITORY_OWNER,,}"

          [ -n "${{ inputs.indy_sdk_url }}"] && echo "::set-output name=indy-sdk-url::${{ inputs.indy_sdk_url }}"
          [ -z "${{ inputs.indy_sdk_url }}"] && echo "::set-output name=indy-sdk-url::${{ env.INDY_SDK_TAG_URL }}v${{ inputs.indy_version }}"

          [ -n "${{ inputs.indy_postgres_url }}"] && echo "::set-output name=indy-postgres-url::${{ inputs.indy_postgres_url }}"
          [ -z "${{ inputs.indy_postgres_url }}"] && echo "::set-output name=indy-postgres-url::${{ env.INDY_SDK_TAG_URL }}v${{ inputs.indy_version }}"

          [ -n "${{ inputs.tag }}" ] && echo "::set-output name=tag::${{ inputs.tag }}"
          [ -z "${{ inputs.tag }}" ] && echo "::set-output name=tag::py${{ matrix.python-version }}-${{ inputs.indy_version }}"

      - uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-base
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Image Metadata
        id: base-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/indy-python
          tags: |
            type=raw,value=${{ steps.info.outputs.tag }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: docker/Dockerfile.indy-base
          tags: ${{ steps.base-meta.outputs.tags }}
          labels: ${{ steps.base-meta.outputs.labels }}
          build-args: |
            python_version=${{ matrix.python-version }}
            indy_version=${{ inputs.indy_version }}
            indy_sdk_url=${{ steps.info.outputs.indy-sdk-url }}
            indy_postgres_url=${{ steps.info.outputs.indy-postgres-url }}
          cache-from: type=local,src=/tmp/.buildx-cache-base
          cache-to: type=local,dest=/tmp/.buildx-cache-base-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-base
          mv /tmp/.buildx-cache-base-new /tmp/.buildx-cache-base
