name: Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
    tests:
      runs-on: ${{ inputs.os }}
      steps:
        - name: Test Python ${{ inputs.python-version }}
          uses: ./.github/actions/run-unit-tests
          with:
            python-version: "3.9"
            os: "ubuntu-latest"
            is_pr: "false"